- name: Install PostgreSQL
  dnf:
    name:
      - postgresql
      - postgresql-contrib
      - postgresql-devel
      - postgresql-server
      - python3-psycopg2  # For postgresql_user
  become: yes

- name: Initialize PostgreSQL
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  become: yes

- name: Create PostgreSQL conf.d directory
  file:
    path: /var/lib/pgsql/data/conf.d
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  become: yes

- name: Add include directory to postgresql.conf
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    line: "include_dir = 'conf.d'"
  become: yes
  notify: Restart PostgreSQL

- name: Copy PostgreSQL configuration
  copy:
    src: "{{ item }}"
    dest: /var/lib/pgsql/data/conf.d/
    owner: postgres
    group: postgres
    mode: 0600
  loop:
    - nondurable.conf
  become: yes
  notify: Restart PostgreSQL

- name: Enable PostgreSQL server
  systemd:
    name: postgresql
    enabled: yes
    state: started
  become: yes

- name: Add PostgreSQL user
  postgresql_user:
    name: "{{ ansible_user }}"
    role_attr_flags: SUPERUSER
