- name: Install PostgreSQL
  dnf:
    name:
      - postgresql
      - postgresql-contrib
      - postgresql-devel
      - postgresql-server
      - python3-psycopg2 # For postgresql_user
  become: yes

- name: Create PostgresSQL directory
  file:
    path: /var/lib/pgsql
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  become: yes

- name: Initialize PostgreSQL
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  become: yes

- name: Enable PostgreSQL server
  systemd:
    name: postgresql
    enabled: yes
    state: started
  become: yes

- name: Configure PostgreSQL nondurable
  postgresql_set:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: checkpoint_timeout
      value: 24h
    - name: fsync
      value: "off"
    - name: full_page_writes
      value: "off"
    - name: max_wal_senders
      value: 0
    - name: synchronous_commit
      value: "off"
    - name: wal_level
      value: minimal
  become: yes
  become_user: postgres
  notify: Restart PostgreSQL

- name: Add PostgreSQL user
  postgresql_user:
    name: "{{ ansible_user_id }}"
    role_attr_flags: SUPERUSER
  become: yes
  become_user: postgres
