- name: Copy pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data/pg_hba.conf
  become: true
  notify: Restart PostgreSQL

- name: Enable PostgreSQL server
  systemd:
    name: postgresql
    enabled: yes
  become: true
