- name: Enable PostgreSQL server
  systemd:
    name: postgresql
    enabled: yes
    state: started
  become: yes

- name: Copy pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data/pg_hba.conf
  become: yes
  notify: Restart PostgreSQL

- name: PostgreSQL non-durable settings
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^#?fsync'
      line: 'fsync = off'
    - regexp: '^#?synchronous_commit'
      line: 'synchronous_commit = off'
    - regexp: '^#?full_page_writes'
      line: 'full_page_writes = off'
  become: yes
  notify: Restart PostgreSQL
