- name: Install Valkey
  dnf:
    name:
      - valkey
      - valkey-compat-redis
  become: yes

- name: Enable Valkey server
  systemd:
    name: valkey
    enabled: yes
    state: started
  become: yes
