#!/bin/bash

. /etc/profile.d/chruby.sh

RUBY_VERSION_REGEXP="^ruby ([0-9]+\.[0-9]+\.[0-9]+)p[0-9]+$"

version=$(bundle platform --ruby 2> /dev/null)
if [[ ${version} =~ ${RUBY_VERSION_REGEXP} ]]; then
    chruby "${BASH_REMATCH[1]}"
    exec bundle "$@"
else
    echo "Unknown Ruby version"
    exit 2
fi
