#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'

raise 'Expected exactly 1 argument' unless ARGV.length == 1

VERSION_REGEXP = /ruby (?<version>\d+\.\d+\.\d+)p\d+/.freeze

parser = Bundler::LockfileParser.new(Bundler.read_file(ARGV[0]))
match = VERSION_REGEXP.match(parser.ruby_version)
print match[:version]
