---
- name: Configure System
  hosts: localhost

  vars:
    cache_dir: "{{ ansible_facts['user_dir'] }}/.cache/system-scripts"

  roles:
    - init
    - dnf
    - desktop
    - docker
    - dotfiles
    - emacs
    - node
    - postgresql
    - python
    - ruby
    - system
    - vagrant
