- hosts: localhost
  roles:
    - desktop
    - django
    - dnf
    - docker
    - dotfiles
    - emacs
    - flatpak
    - mariadb
    - nodejs
    - postgresql
    - python
    - redis
    - system
