- name: Install additional packages
  dnf:
    name:
      - dconf-editor
      - gimp
      - python3-psutil  # For dconf
  become: yes

- name: Tweak GNOME configuration
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
      value: "true"
    - key: /org/gnome/desktop/peripherals/touchpad/click-method
      value: "'areas'"
