- name: Install psutil
  dnf:
    name:
      # TODO: Remove python2-psutil when Python 2 support is dropped.
      - python2-psutil  # For dconf
      - python3-psutil  # For dconf
  become: yes

- name: Enable Night Light
  dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"
