- name: Install additional packages
  dnf:
    name:
      - dconf-editor
      - deluge-gtk
      - gimp
      - python3-psutil  # For dconf
  become: yes

- name: Configure GNOME Dash favorite apps
  dconf:
    key: /org/gnome/shell/favorite-apps
    value:
      - firefox.desktop
      - org.gnome.Terminal.desktop
      - emacsclient.desktop
      - mozilla-thunderbird.desktop
      - rhythmbox.desktop
      - org.gnome.Nautilus.desktop
      - virtualbox.desktop
      - com.slack.Slack.desktop

- name: Tweak GNOME configuration
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
      value: "true"
    - key: /org/gnome/desktop/peripherals/touchpad/click-method
      value: "'areas'"
