- name: Install psutil
  dnf:
    name: python2-psutil  # For dconf
  become: yes

- name: Enable Night Light
  dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"
