- name: Install Mercurial Evolve Extension
  pip:
    name: hg-evolve
    extra_args: --user

- name: Copy dot files
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
  with_items:
    - gitconfig
    - gitignore
    - hgrc
