- name: Install meld
  dnf:
    name: meld
  become: yes

- name: Install Mercurial Evolve Extension
  pip:
    name: hg-evolve
    executable: pip2
    extra_args: --user

- name: Copy dot files
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
  with_items:
    - gitconfig
    - gitignore
    - hgrc
