- name: Install meld
  dnf:
    name: meld
  become: yes

- name: Copy dot files
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
  loop:
    - gitconfig
    - gitignore
    - hgrc
    - ignore
    - ripgreprc

- name: Custom environment variables
  lineinfile:
    path: ~/.bash_profile
    line: "export RIPGREP_CONFIG_PATH={{ ansible_env.HOME }}/.ripgreprc"
    regexp: \bRIPGREP_CONFIG_PATH=
