#!/usr/bin/env python

import subprocess
import functools


class Git:
    def run(self, cmd, *args):
        r = subprocess.run(
            ["git", cmd, *args], stdout=subprocess.PIPE, text=True, check=True
        )
        return r.stdout.strip()

    def __getattr__(self, name):
        name = name.replace("_", "-")
        return functools.partial(self.run, name)


git = Git()

# Halt if there are uncommitted changes.
git.diff("--exit-code")

current_branch = git.branch("--show-current")
git.checkout("--detach")
try:
    git.fetch("--all", "--prune")

    upstream_branches = git.for_each_ref(
        "--format=%(refname:lstrip=3)", "refs/remotes/upstream/"
    ).split()

    fetch_refspec = [f"{branch}:{branch}" for branch in upstream_branches]
    git.fetch("upstream", *fetch_refspec)
    git.push("--set-upstream", "--tags", "origin", *upstream_branches)
finally:
    if current_branch:
        git.checkout(current_branch)
