#!/usr/bin/env python

import argparse
import functools
import subprocess


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("branches", nargs="*")
    return parser.parse_args()


class Git:
    def run(self, cmd, *args):
        r = subprocess.run(
            ["git", cmd, *args], stdout=subprocess.PIPE, text=True, check=True
        )
        return r.stdout.strip()

    def __getattr__(self, name):
        name = name.replace("_", "-")
        return functools.partial(self.run, name)


args = parse_args()

git = Git()

# Halt if there are uncommitted changes.
git.diff("--exit-code")

current_branch = git.branch("--show-current")
git.checkout("--detach")
try:
    git.fetch("--all", "--prune")

    if args.branches:
        upstream_branches = args.branches
    else:
        upstream_branches = git.for_each_ref(
            "--format=%(refname:lstrip=3)", "refs/remotes/upstream/"
        ).split()

    fetch_refspec = [f"{branch}:{branch}" for branch in upstream_branches]
    git.fetch("upstream", *fetch_refspec)
    git.push("--set-upstream", "--tags", "origin", *upstream_branches)
finally:
    if current_branch:
        git.checkout(current_branch)
