- name: Install libselinux-python
  dnf:
    name: libselinux-python
  become: yes

- name: Install ansible-lint
  dnf:
    name: ansible-lint
  become: yes

- name: Install DNF plugins
  dnf:
    name: dnf-automatic
  become: yes

- name: Enable DNF automatic timer
  systemd:
    name: dnf-automatic-install.timer
    enabled: yes
    state: started
  become: yes

- name: Install dot files
  include_role:
    name: dotfiles

- name: Install and configure Emacs
  include_role:
    name: emacs

- name: Install flatpak applications
  include_role:
    name: flatpak

- name: Install and configure NGINX
  include_role:
    name: nginx

- name: Install and configure Node.js
  include_role:
    name: nodejs

- name: Install PHP
  include_role:
    name: php

- name: Install and configure PostgreSQL
  include_role:
    name: postgresql

- name: Install and configure MariaDB
  include_role:
    name: mariadb

- name: Install Python
  include_role:
    name: python

- name: Install and configure RabbitMQ
  include_role:
    name: rabbitmq

- name: Install and configure Redis
  include_role:
    name: redis

- name: Configure desktop
  include_role:
    name: desktop
