- name: Install libselinux-python
  dnf:
    name: libselinux-python
  become: true

- include_role:
    name: dotfiles

- include_role:
    name: emacs

- include_role:
    name: postgresql

- include_role:
    name: redis

- include: php.yml

- name: Update packages
  dnf:
    name: "*"
    state: latest
  become: true
