- name: Update packages
  dnf:
    name: "*"
    state: latest
  become: true

- name: Install libselinux-python
  dnf:
    name: libselinux-python
  become: true

- include_role:
    name: dotfiles

- include_role:
    name: emacs

- include: php.yml
