- name: Set time zone
  timezone:
    name: America/Vancouver

- import_tasks: ssh.yml

- name: Install additional packages
  dnf:
    name:
      - "@multimedia"
      - "@sound-and-video"
      - awscli
      - ccache
      - gitk
      - graphviz
      - gstreamer1-libav
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-ugly-free
      - jq
      - openldap-devel
      - rpmconf
      - vagrant
      - VirtualBox
      - x264
  become: yes

- name: Install ansible-lint
  dnf:
    name: ansible-lint
  become: yes

- name: Install scripts
  copy:
    src: scripts/
    dest: ~/.local/bin/
    mode: 0755
