- name: Install libselinux-python
  dnf:
    name: libselinux-python
  become: true

- name: Install DNF plugins
  dnf:
    name: dnf-automatic
  become: true

- name: Enable DNF automatic timer
  systemd:
    name: dnf-automatic-download.timer
    enabled: yes
    state: started
  become: true

- include_role:
    name: dotfiles

- include_role:
    name: emacs

- include_role:
    name: nodejs

- include_role:
    name: php

- include_role:
    name: postgresql

- include_role:
    name: rabbitmq

- include_role:
    name: redis
