---
- name: Set time zone
  community.general.timezone:
    name: America/Vancouver

- name: Configure SSH
  ansible.builtin.import_tasks: ssh.yaml

- name: Install additional packages
  ansible.builtin.dnf:
    name:
      - ansible-lint
      - ccache
      - gitk
      - graphviz
      - jq
      - kernel-devel
      - ollama
      - rpmconf
      - sqlite-devel
  become: true

- name: Install scripts
  ansible.builtin.copy:
    src: scripts/
    dest: ~/.local/bin/
    mode: "0775"

- name: Remove system AWS CLI
  ansible.builtin.dnf:
    name: awscli
    state: absent
  become: true

- name: Download AWS CLI version 2
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "{{ cache_dir }}/"
    mode: "0600"
  register: system_awscliv2

- name: Unzip AWS CLI version 2
  ansible.builtin.unarchive:
    src: "{{ system_awscliv2.dest }}"
    dest: "{{ cache_dir }}/"
    creates: "{{ cache_dir }}/aws"

- name: Install AWS CLI version 2
  ansible.builtin.command:
    cmd: "{{ cache_dir }}/aws/install"
    creates: /usr/local/bin/aws
  become: true
