- name: Install libselinux-python
  dnf:
    name: libselinux-python
  become: true

- name: Install DNF plugins
  dnf:
    name: dnf-automatic
    state: latest
  become: true
  notify: Restart DNF automatic timer

- name: Enable DNF automatic timer
  systemd:
    name: dnf-automatic-download.timer
    enabled: yes
  become: true

- include_role:
    name: dotfiles

- include_role:
    name: emacs

- include_role:
    name: postgresql

- include_role:
    name: redis

- include: php.yml

- name: Update packages
  dnf:
    name: "*"
    state: latest
  become: true
