- name: Set time zone
  timezone:
    name: America/Vancouver

- name: Install RPM Fusion
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  become: yes

- name: Install additional packages
  dnf:
    name:
      - "@multimedia"
      - "@sound-and-video"
      - ccache
      - graphviz
      - gstreamer-ffmpeg
      - gstreamer-plugins-bad
      - gstreamer-plugins-bad-free
      - gstreamer-plugins-bad-free-extras
      - gstreamer-plugins-bad-nonfree
      - gstreamer-plugins-good
      - gstreamer-plugins-good-extras
      - gstreamer-plugins-ugly
      - gstreamer1-libav
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-nonfree
      - gstreamer1-plugins-good-extras
      - jq
      - rpmconf
      - x264
  become: yes

- name: Install libselinux-python
  dnf:
    name: libselinux-python
  become: yes

- name: Install ansible-lint
  dnf:
    name: ansible-lint
  become: yes

- name: Configure DNF
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  become: yes
  with_items:
    - option: fastestmirror
      value: 1
    - option: max_parallel_downloads
      value: 10

- name: Install DNF plugins
  dnf:
    name: dnf-automatic
  become: yes

- name: Enable DNF automatic timer
  systemd:
    name: dnf-automatic-install.timer
    enabled: yes
    state: started
  become: yes

- name: Install additional roles
  include_role:
    name: "{{ role }}"
  with_items:
    - desktop
    - docker
    - dotfiles
    - emacs
    - flatpak
    - mariadb
    - nginx
    - nodejs
    - php
    - postgresql
    - python
    - redis
  loop_control:
    loop_var: role

- name: Install additional packages
  dnf:
    name:
      - latexmk
      - texlive-scheme-full
  become: yes
