- name: Install RPM Fusion
  dnf:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-29.noarch.rpm
  become: yes

- name: Install additional packages
  dnf:
    name:
      - "@multimedia"
      - "@sound-and-video"
      - graphviz
      - gstreamer-ffmpeg
      - gstreamer-plugins-bad
      - gstreamer-plugins-bad-free
      - gstreamer-plugins-bad-free-extras
      - gstreamer-plugins-bad-nonfree
      - gstreamer-plugins-good
      - gstreamer-plugins-good-extras
      - gstreamer-plugins-ugly
      - gstreamer1-libav
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-nonfree
      - gstreamer1-plugins-good-extras
      - jq
      - x264
  become: yes

- name: Install libselinux-python
  dnf:
    name: libselinux-python
  become: yes

- name: Install ansible-lint
  dnf:
    name: ansible-lint
  become: yes

- name: Configure DNF
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  become: yes
  with_items:
    - option: fastestmirror
      value: True
    - option: max_parallel_downloads
      value: 10

- name: Install DNF plugins
  dnf:
    name: dnf-automatic
  become: yes

- name: Enable DNF automatic timer
  systemd:
    name: dnf-automatic-install.timer
    enabled: yes
    state: started
  become: yes

- name: Install Docker
  include_role:
    name: docker

- name: Install dot files
  include_role:
    name: dotfiles

- name: Install and configure Emacs
  include_role:
    name: emacs

- name: Install flatpak applications
  include_role:
    name: flatpak

- name: Install and configure NGINX
  include_role:
    name: nginx

- name: Install and configure Node.js
  include_role:
    name: nodejs

- name: Install PHP
  include_role:
    name: php

- name: Install and configure PostgreSQL
  include_role:
    name: postgresql

- name: Install and configure MariaDB
  include_role:
    name: mariadb

- name: Install Python
  include_role:
    name: python

- name: Install and configure RabbitMQ
  include_role:
    name: rabbitmq

- name: Install and configure Redis
  include_role:
    name: redis

- name: Configure desktop
  include_role:
    name: desktop

- name: Install additional packages
  dnf:
    name:
      - latexmk
      - texlive-scheme-full
  become: yes
