# TODO: Use flatpak_remote
# https://docs.ansible.com/ansible/latest/modules/flatpak_remote_module.html
#
# Blocked by https://github.com/ansible/ansible/issues/46994
- name: Add Flathub repository
  command: flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: ~/.local/share/flatpak/repo/refs/remotes/flathub

- name: Install flatpak applications
  flatpak:
    name: "{{ item }}"
    method: user
  with_items:
    - com.skype.Client
    - com.slack.Slack
    - us.zoom.Zoom
