- name: Add Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak applications
  flatpak:
    name: "{{ item }}"
    method: user
  loop:
    - com.skype.Client
    - com.slack.Slack
    - org.signal.Signal
    - us.zoom.Zoom
