- name: Add Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

# TODO: Pass package names as a list.
# https://github.com/ansible-collections/community.general/pull/267
- name: Install flatpak applications
  flatpak:
    name: "{{ item }}"
    method: user
  loop:
    - com.slack.Slack
    - com.spotify.Client
    - us.zoom.Zoom
