- name: Install MariaDB
  dnf:
    name:
      - mariadb
      - mariadb-common
      - mariadb-devel
      - mariadb-server
  become: yes

- name: Copy MariaDB configuration
  copy:
    src: "{{ item }}"
    dest: /etc/my.cnf.d/
    owner: root
    group: root
    mode: 0644
  loop:
    - utf8.cnf
    - nondurable.cnf
  become: yes

- name: Start MariaDB server
  systemd:
    name: mariadb
    enabled: yes
    state: started
  become: yes

- name:
  command: mysqladmin -u root password ''
  become: yes

- name:
  shell: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
