- name: Install MySQL
  dnf:
    name:
      - community-mysql
      - community-mysql-common
      - community-mysql-devel
  become: yes

- name: Copy MySQL configuration
  copy:
    src: client.cnf
    dest: /etc/my.cnf.d/
    owner: root
    group: root
    mode: 0644
  become: yes
