- name: Install Emacs
  dnf:
    name:
      - emacs
      - levien-inconsolata-fonts
      - ripgrep
  become: yes
  notify: Restart Emacs daemon

- name: Emacs configuration
  git:
    repo: git@github.com:jdufresne/emacs-init.git
    dest: ~/.emacs.d
    force: yes
  notify: Restart Emacs daemon

- name: Override emacs.service
  template:
    dest: ~/.config/systemd/user/emacs.service.d/
    src: override.conf
  notify: Restart Emacs daemon

- name: Install Emacs client desktop file
  copy:
    dest: ~/.local/share/applications/
    src: emacsclient.desktop

- name: Enable Emacs daemon
  systemd:
    name: emacs
    scope: user
    enabled: yes
    state: started
