- name: Install Emacs
  dnf:
    name: emacs
  become: true
  notify: Restart Emacs daemon

- name: Enable Emacs daemon
  systemd:
    name: emacs
    user: yes
    enabled: yes

- name: Emacs configuration
  git:
    repo: git@github.com:jdufresne/emacs-init.git
    dest: ~/.emacs.d
    force: yes
  notify: Restart Emacs daemon

- name: Install Emacs client desktop file
  copy:
    dest: ~/.local/share/applications/
    src: emacsclient.desktop
