- name: Install Django dependencies
  dnf:
    name:
      # Pillow
      - freetype-devel
      - fribidi-devel
      - harfbuzz-devel
      - lcms2-devel
      - libjpeg-devel
      - libraqm-devel
      - libtiff-devel
      - libwebp-devel
      - openjpeg2-devel
      - zlib-devel
      # memcached
      - libmemcached-devel
      - memcached
      # Selenium
      - chromedriver
      - chromium
  become: yes

- name: Download geckodriver
  get_url:
    url: https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
    dest: ~/.local/bin/
  register: geckodriver

- name: Extract geckodriver
  unarchive:
    src: "{{ geckodriver.dest }}"
    dest: ~/.local/bin/
    remote_src: yes
