- name: Install Django dependencies
  dnf:
    name:
      # Pillow
      - freetype-devel
      - fribidi-devel
      - harfbuzz-devel
      - lcms2-devel
      - libjpeg-devel
      - libraqm-devel
      - libtiff-devel
      - libwebp-devel
      - openjpeg2-devel
      - zlib-devel
      # memcached
      - libmemcached-devel
      - memcached
  become: yes

- name: Get geckodriver release information
  uri:
    url: https://api.github.com/repos/mozilla/geckodriver/releases/latest
    headers:
      Accept: application/vnd.github.v3+json
  register: geckodriver_release

- name: Download geckodriver
  get_url:
    url: "{{ geckodriver_release.json | json_query('assets[*].browser_download_url') | select('match', '^.*-linux64\\.tar\\.gz$') | first }}"
    dest: "{{ cache_dir }}/"
  register: geckodriver

- name: Extract geckodriver
  unarchive:
    src: "{{ geckodriver.dest }}"
    dest: ~/.local/bin/
    remote_src: yes
