- name: Install Django dependencies
  dnf:
    name:
      # Pillow
      - freetype-devel
      - fribidi-devel
      - harfbuzz-devel
      - lcms2-devel
      - libjpeg-devel
      - libraqm-devel
      - libtiff-devel
      - libwebp-devel
      - openjpeg2-devel
      - zlib-devel
      # memcached
      - libmemcached-devel
      - memcached
  become: yes
