---
- name: Download nvm
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ node_nvm_version }}/install.sh"
    dest: "{{ cache_dir }}/nvm-{{ node_nvm_version }}.sh"
    mode: "0600"
  register: node_nvm_download

- name: Create ~/.bashrc.d/nvm.sh
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc.d/nvm.sh"
    state: touch
    mode: "0664"

- name: Check installed nvm
  ansible.builtin.slurp:
    src: "{{ ansible_facts['env']['HOME'] }}/.nvm/package.json"
  register: node_nvm_package_json
  changed_when: false
  failed_when: false

- name: Parse installed nvm version
  ansible.builtin.set_fact:
    node_nvm_installed_version: >-
      {{ (node_nvm_package_json.content | b64decode | from_json).version }}
  when: node_nvm_package_json is succeeded

- name: Install nvm
  ansible.builtin.command:
    argv:
      - sh
      - "{{ node_nvm_download.dest }}"
  environment:
    PROFILE: "{{ ansible_facts['env']['HOME'] }}/.bashrc.d/nvm.sh"
  when: >
    node_nvm_package_json is failed
    or
    node_nvm_installed_version != node_nvm_version
  changed_when: true

- name: Install Node.js versions
  ansible.builtin.shell:
    cmd: |
      export NVM_DIR=${HOME}/.nvm
      . ${NVM_DIR}/nvm.sh
      nvm install {{ item }}
    creates: "{{ ansible_facts['env']['HOME'] }}/.nvm/versions/node/{{ item }}"
  loop: "{{ node_versions }}"

- name: Configure npm
  ansible.builtin.copy:
    src: npmrc
    dest: ~/.npmrc
    mode: "0600"

- name: Copy bashrc script
  ansible.builtin.copy:
    src: nvm-auto.sh
    dest: ~/.bashrc.d/
    mode: "0664"
