#!/bin/bash

set -e
set -u

root=$(git rev-parse --show-toplevel)

cat << EOF > "${root}/tests/test_postgresql.py"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django_default',
    },
    'other': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django_other',
    }
}

SECRET_KEY = "django_tests_secret_key"

# Use a fast hasher to speed up tests.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.MD5PasswordHasher',
]

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
EOF

pushd "${root}/tests"
PYTHONPATH=${root} python -b -Wa runtests.py --noinput --settings test_postgresql "$@"
popd
