#!/bin/sh

set -e
set -u

if [[ ! -v PYTHON ]]; then
    PYTHON=python3.9
fi

root=$(git rev-parse --show-toplevel)
proj=$(basename ${root})

rm -rf ~/.virtualenvs/${proj}
${PYTHON} -m venv ~/.virtualenvs/${proj}
echo . ~/.virtualenvs/${proj}/bin/activate
