#!/bin/sh

set -e
set -u

if [[ ! -v PYTHON ]]; then
    PYTHON=python3.9
fi

root=$(git rev-parse --show-toplevel)
proj=$(basename ${root})

rm -rf ~/.venv/${proj}
${PYTHON} -m venv ~/.venv/${proj}
echo . ~/.venv/${proj}/bin/activate
