#!/bin/bash

set -euo pipefail

url=$(curl \
          --fail \
          --no-progress-meter \
          --write-out %{redirect_url} \
          https://zoom.us/client/latest/zoom_x86_64.rpm)
version=$(sed -e 's|^https://cdn\.zoom\.us/prod/\(.*\)/zoom_x86_64.rpm$|\1|g' <<< "${url}")
path="${HOME}/Downloads/zoom-${version}.x86_64.rpm"
curl -o "${path}" "${url}"
sudo dnf install --assumeyes "${path}"
