#!/usr/bin/env python

import subprocess
from pathlib import Path


def main():
    p = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    )
    root = Path(p.stdout.strip())
    project = root.name

    database = f"{project}_template"
    subprocess.run(["dropdb", "--force", "--if-exists", database], check=True)
    subprocess.run(["createdb", database], check=True)
    subprocess.run(
        [
            "psql",
            "-f",
            Path.home().joinpath("dumps", f"{project}-scrubbed.sql"),
            database,
        ],
        check=True,
    )


if __name__ == "__main__":
    main()
